version: 3.4.
services:
  backend:
    container_name: backend
    build:
      context: ./
      target: debug
    volumes:
      - ./:/app/
    ports:
      - 3000:3000
      - 2345:2345
    security_opt:
      - 'seccomp:unconfined'
